--- 
- hosts: localhost 
  name: ESXi Basic Configuration 
  gather_facts: false
  vars:
    esxi_login: &esxi_login
      hostname: '{{ item.name }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'   
      validate_certs: no 
    tsm_policy: on
    tsm_state: present 
  vars_files: 
    vars.yml
  tasks:
# Enable / Disable SSH on Host 
  - name: Enable SSH (TSM-SSH) for an ESXi Host with Service policy
    community.vmware.vmware_host_service_manager:
     <<: *esxi_login
     esxi_hostname: '{{ esxi_address }}'
     service_name: TSM-SSH
     service_policy: on
     state: present # Change to Absent if you want to disable SSH
    delegate_to: localhost
    loop: '{{ esxi_info }}'
  - name: Enable ESX Shell (TSM) setting for an ESXi Host with Service policy
    community.vmware.vmware_host_service_manager:
     <<: *esxi_login
     esxi_hostname: '{{ item.name }}'
     service_name: TSM
     service_policy: on
     state: present # Change to Absent if you want to disable SSH
    delegate_to: localhost
    loop: '{{ esxi_info }}'